package GUIComponents;
import java.awt.GridLayout;
import javax.swing.*;
import Tickets.*;

/**
 * Nice panel for displaying id, status, date opened, date closed, impact, 
 * and priority of a panel in a pretty bordered box that says "Basics".  
 * 
 * Note:  The only editable/non-autogenerated fields are status, impact, and 
 * priority  so this panel should always disable changing the 
 * the id, date opened, date closed components.
 * 
 * @author ryank
 *
 */
public class TicketBasicInfoPanel  extends JPanel {

	private static final long serialVersionUID = 1L; //For serialization - ignore this.
	
	private JLabel idLabel; //ID  
	private JTextField idTF;  

	private JLabel statusLabel; //status
	private JTextField statusTF;

	private JLabel doLabel; //date opened
	private JTextField doTF;
	
	private JLabel dcLabel;  //Date closed 
	private JTextField dcTF;
	
	private JLabel impLabel; //IMpact
	protected JComboBox<Impact> impCombo;

	private JLabel prLabel; //Priority
	protected JComboBox<Priority> prCombo;


	/**
	 * Since no ticket is passed in, this constructor
	 * is expected to be used only when users are CREATING/SUBMITTING
	 * a new ticket.
	 */
	public TicketBasicInfoPanel()
	{
		//initialize the components
		initComps();
		
		//set them up for creating a new ticket
		setAppearanceForTicketCreation();
	}
	
	/**
	 * Initializes the components on the panel.
	 */
	public void initComps()
	{
		idLabel = new JLabel("Ticket ID: ");
		idTF = new JTextField(15);

		statusLabel = new JLabel("Status: ");
		statusTF = new JTextField(15);
		
		doLabel = new JLabel("Date Opened: ");
		doTF = new JTextField(15);

		dcLabel = new JLabel("Date Closed: ");
		dcTF = new JTextField(15);

		impLabel = new JLabel("Impact: ");
		impCombo = new JComboBox<Impact>(Impact.values());
		
		prLabel = new JLabel("Priority: ");
		prCombo = new JComboBox<Priority>(Priority.values());
		
		setBorder(BorderFactory.createTitledBorder("Basics"));
		setLayout(new GridLayout(6,2));
		
		add(idLabel);
		add(idTF);
		
		add(statusLabel);
		add(statusTF);

		add(doLabel);
		add(doTF);
		
		add(dcLabel);
		add(dcTF);
		
		add(impLabel);
		add(impCombo);
	
		add(prLabel);
		add(prCombo);
	}

	/**
	 * Sets the appearance when this panel is being used 
	 * for ticket creation, ie, disables id, status, date open/closed 
	 * since they are autogeneated and sets them show "N/A" 
	 */
	private void setAppearanceForTicketCreation()
	{
		//Set id, status, date open/closed to N/A as 
		//Users won't input this information - it
		//will be populated for them.
		idTF.setText("N/A"); 
		statusTF.setText("N/A");
		doTF.setText("N/A");
		dcTF.setText("N/A");
		
		//Disable the same fields 
		//so that user won't attempt to edit
		//them at creation
		idTF.setEnabled(false);  
		statusTF.setEnabled(false);
		doTF.setEnabled(false);
		dcTF.setEnabled(false);
	}
	
	/**
	 * Returns what value of impact has been chosen (helpful when creating
	 * a new ticket or modifying an old one).
	 * @return The Chosen impact
	 */
	public Impact getImpact()
	{
		return (Impact) impCombo.getSelectedItem();
	}
	
	/**
	 * Returns what value of priority has been chosen (helpful when creating
	 * a new ticket or modifying an old one).
	 * @return The Chosen Priority
	 */
	public Priority getPriority()
	{
		return (Priority) prCombo.getSelectedItem();
	}

	public void setImpCombo(JComboBox<Impact> impCombo) {
		this.impCombo = impCombo;
	}

	public void setPrCombo(JComboBox<Priority> prCombo) {
		this.prCombo = prCombo;
	}
	
	
	/**
	 * Sets the text fields and combo boxes so that it displays
	 * the id/status/date opened/date closed/impact/priority
	 * of the passed in ticket
	 * 
	 * @param ticket The ticket whose info we wish to display
	 */
	public void setTicketInfo(Ticket ticket)
	{
		idTF.setText(""+ticket.getTicketID()); //ticket ID is an int so making it a string
		
		if (ticket.isOpen())
			statusTF.setText("OPEN");
		else
			statusTF.setText("CLOSED");
			

		doTF.setText(ticket.getDateOpened());
		dcTF.setText(ticket.getDateClosed());
		
		impCombo.setSelectedItem(ticket.getImpact());
		prCombo.setSelectedItem(ticket.getPriority());
	}

	/**
	 * Sets the inital component values back to defaults.
	 */
	public void resetInitialValues()
	{
		idTF.setText("N/A"); 
		statusTF.setText("N/A");
		doTF.setText("N/A");
		dcTF.setText("N/A");
		prCombo.setSelectedIndex(0);
		impCombo.setSelectedIndex(0);
	}
	
	
	/**
	 * Disables all information so that the panel is non-editable.
	 * Expected to be used when a user is viewing his/her open tickets.
	 */
	public void disableAll()
	{
		impCombo.setEnabled(false);
		prCombo.setEnabled(false);
		idTF.setEnabled(false);  
		statusTF.setEnabled(false);
		doTF.setEnabled(false);
		dcTF.setEnabled(false);
	}
	

}
